### ISSUE TITLE
NullPointerException when creating new option with specified id

### ISSUE THREAD

**Issue by mzachar** [codeclou/customfield-editor-plugin#13]
Hi,

I'm having issue creating new option for cascading picker (using rest api explorer).

When I specify the following JSON
```
{
  "optionvalue": "xyz",
  "id": 1005
}
```

it will throw following error 500 with NPE.
```
{
  "statusCode": 500,
  "subCode": 5002003,
  "message": "Unexpected Error: java.lang.NullPointerException"
}
```

This is the full curl
```
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" --header "Authorization: Basic REMOVED" -d "{
  \"optionvalue\": \"xyz\",
  \"id\": 1005
}" "https://REMOVED/rest/jiracustomfieldeditorplugin/1.2/user/customfields/12400/contexts/13800/options"
```

How ever when I remove the ID field it works as intended.
```
{
  "optionvalue": "xyz2"
}
```

I also tried different IDs but nothing seems to work. I even look at what was the last option ID (e.g. 1004) and used that one incremented by one (e.g. 1005) which did not work neither. But when I created new option without specifying the ID that was the ID which get used(e.g. 1005). Which implies it was not used when I was trying the request with `"id": 1005` field.

Plugin Version: 1.2.3
Jira Version: v7.2.4

Do you have any ideas what could be wrong?

**Comment by clouless** [comment]
When creating new options never specify an ID.

So this is correct:

```
{
  "optionvalue": "xyz2"
}
```

**Comment by mzachar** [comment]
Well I was hoping to use ID from third system which is source of the options so I don't have to relay on human readable values to link them.

So if I understand it correctly it is not supported to create options with custom IDs?

**Comment by clouless** [comment]
I am afraid no. The plugin just provides access to the built-in JIRA functionality.
And since JIRA does not provide such a field you cannot store that information.

if your IDs are numeric you could misuse the "sequence" field to store the custom-id, but when someone sorts the field, the information will get lost ....

So there is practically no way to reference it. You would have to do something like

```
{
  "optionvalue": "Foo (ID:44334)"
}
```

**Comment by mzachar** [comment]
Thank you for your fast response.

In that case I think I will create custom mapping table which will store the generated ID which jira assigns to the created options and link that to the third party system ID.

**Comment by clouless** [comment]
Sounds good :)
If you need any further help, feel free to open another ticket.
