### ISSUE TITLE
[CEP-19] REST API: Change of option only in case returns error

### ISSUE THREAD

**Issue by FlexUli** [codeclou/customfield-editor-plugin#19]
If you change an option on in case (eg. from "foo here" to "Foo here"), the PUT request returns with an error:
{
          'message' => 'validation errors',
          'subCode' => '400000',
          'errors' => [
                        {
                          'name' => 'optionvalue',
                          'message' => 'This option value does already exist. Option values need to be unique.'
                        }
                      ],
          'statusCode' => '400'
        };

**Comment by clouless** [comment]
I will include this in next major release.
For now try a workaround: rename to 'foo here X' and back to ' Foo Here'.

**Comment by FlexUli** [comment]
Thanks.
I already implemented this workaround... it works.

**Comment by clouless** [comment]
backlog items are closed until scheduled for next release.

**Comment by clouless** [comment]
Duplicate of #58 [CEP-59]
