### ISSUE TITLE
Change of option value does not change the value in used issues

### ISSUE THREAD

**Issue by FlexUli** [codeclou/customfield-editor-plugin#21]
If I modify an option (value), this change is not reflected in the issues, where this option value is used.
How to reproduce:
1. Generate a Select Field with option 'A'
2. Generate an Issue, use this select field, and set to 'A'
3. Modify value of this option from 'A' to 'B' (by REST or Field Editor)
4. View again the issue: It's still 'A'.

If I open the edit box for the field, the value 'B' is visible. But hitting OK or Abort does not change it to the new value. Indexing this issue does also not help.
Btw: If I change the option value in administration section of Jira-GUI, this works correctly (means new value B is immediately visible in the issues).

**Comment by clouless** [comment]
Hi,

this was already fixed in Plugin version 1.2.2. See: #5
Please update to v1.2.2 or newer.

thx.
