### ISSUE TITLE
Permission Editor does not allow to add user

### ISSUE THREAD

**Issue by mliebelt** [codeclou/customfield-editor-plugin#22]
We face currently the following problem:

- I go to "Custom Field Editor"
- Select there "Permission Editor"
- Select then "Edit" for one custom field.
- Enter in the list of users the Id of a user.
- The spinner runs forever (> 120 seconds waited).

The same works on another server without a problem (answers in < 1 second all the time). We have checked the log of JIRA, but did not get any notice about the problem. What can we do to debug the problem further?

![image](https://cloud.githubusercontent.com/assets/520039/24612976/25b5e78c-1887-11e7-84ee-7757c8439ad0.png)

**Comment by clouless** [comment]
I am sorry to hear that.
Can you first of all do a **Health Check** and see if all is green:

![](https://camo.githubusercontent.com/f480dc4e5eea003944ce77f0b43236cd310b4b86/68747470733a2f2f636f6465636c6f752e6769746875622e696f2f646f636b65722d61746c61737369616e2d6a6972612d646174612d63656e7465722f696d672f636c75737465722d30372d6865616c74682d636865636b732e706e67)

The second thing you can do is to activate Google Chromes Developer Toolbar, 
and use the **Network-Tab** to check for HTTP Request Errors.
The GUI itself uses the REST API so there seems to be a problem with the REST Call.

I will soon provide a screenshot about it.

**Comment by clouless** [comment]
Here is an article about using DevTools: https://developers.google.com/web/tools/chrome-devtools/network-performance/

And here is how you debug:

![debug-rest-calls](https://cloud.githubusercontent.com/assets/12599965/24622215/81d85fc8-18a4-11e7-8a10-5874cd3f62bd.gif)

Please send me a screenshot of the REQUEST and RESPONSE, thx.
(you can blur out hostnames)

**Comment by mliebelt** [comment]
After checking again with the developer tools of Chrome, I found the following in the console:

![image](https://cloud.githubusercontent.com/assets/520039/24631001/1610b1e4-18bf-11e7-8733-d869ea33f1bb.png)

So the operation team has more rights in our JIRA installation than I have, on the other server I mentioned, I have full system administration rights. It seemed to be sufficient to use all features of the custom field editor plugin, but wasn't.

So I think you could close the ticket then.

**Comment by clouless** [comment]
With the next version 1.3.0 I will resolve this issue.
So that normal admins and sysadmins can use the permission editor.
See #9

I will release next week. Sorry to not having thought of that :sweat:
There is currently no real error message. But in v1.3.0 this will all be fixed 😄

**Comment by clouless** [comment]
Implemented with v1.3.0.
You can now download version 1.3.0 from the [Atlassian marketplace](https://marketplace.atlassian.com/plugins/jiracustomfieldeditorplugin/server/overview). 
See [Release Notes](https://codeclou.io/customfield-editor-plugin/1.3.0/release-notes/).
