### ISSUE TITLE
Documentation 404

### ISSUE THREAD

**Issue by lhotakj** [codeclou/customfield-editor-plugin#23]
Hi,
could you please make working the documentation?
I am getting 404 when opening it from the Marketplace:
https://codeclou.io/products/customfield-editor-plugin/getting-started/introduction/
or
https://codeclou.io/products/customfield-editor-plugin/1.2/rest-api/ 

Thanks a lot,
Jarda

**Comment by clouless** [comment]
Please use:

https://codeclou.io/customfield-editor-plugin/1.2.3/

I will correct that immediately.
