### ISSUE TITLE
Logged activity in jira log file

### ISSUE THREAD

**Issue by cmg1986** [codeclou/customfield-editor-plugin#24]
Hi, I am trying this add-on for my enterprise instance. I want to understand whether this add-on has any logging capability so that jira admin can verify which user made changes in custom field.
If we provide permission on context to a jira group & we need to identify who made changes in that particular context's custom field then how is this possible?

This is logged activity in any jira log file?

Thanks
CM

**Comment by clouless** [comment]
hi, at the moment such an **audit logging** is not implemented.
There is currently no way of telling who did what.

But I will think about it and maybe implement it. It depends on how intrusive the change is,
and if it would slow down the plugin too much.

cheers,
Bernhard

**Comment by clouless** [comment]
This has been implemented with #105 in App version 2.9.0. See the Atlassian Marketplace or the [Release Notes](https://codeclou.io/customfield-editor-for-jira/latest/release-notes/).
