### ISSUE TITLE
FR - support for fields from the 'Multi Level Cascading Select' plugin

### ISSUE THREAD

**Issue by nneul** [codeclou/customfield-editor-plugin#26]
Not sure if this is at all feasible, but would love to see support for this modules field type added:

https://marketplace.atlassian.com/plugins/com.sourcesense.jira.plugin.cascadingselect/server/overview

**Comment by clouless** [comment]
hi @nneul 
Currently I am not planning to support other customfield types than the built in ones.
Main reason is the compatibility issues and if the Plugin Vendor changes the API My plugin breakes as well.

But I will think about it and put the task in the backlog.
cheers,

**Comment by clouless** [comment]
Done with 2.11.0 see blog post 

https://codeclou.io/blog/2021/07/customfield-editor-for-jira-now-supports-multi-level-cascading-select-custom-field-type/
