### ISSUE TITLE
Support for editing text field default value

### ISSUE THREAD

**Issue by RJanata** [codeclou/customfield-editor-plugin#27]
You can edit default values for supported custom fields. Common text fields (single or multi-line) can also have their default value (predefined text) but this is not currently supported.

It would be great if the addon can support editing default values for text fields. Thanks for considering this.

Thanks for awesome addon, @clouless.

**Comment by clouless** [comment]
Hi Rjanta,

That is actually a good idea :)

Currently I am in the middle of a big refactoring of the frontend,
and will implement new features afterwards.

But I will put the task in the backlog, so that I do not loose sight of it :)

cheers

**Comment by RJanata** [comment]
Thanks Bernhard for a quick response and considering this for future :)
