### ISSUE TITLE
Display user/group permission on Field list at Permission Editor

### ISSUE THREAD

**Issue by RJanata** [codeclou/customfield-editor-plugin#28]
Hi Bernhard,

except #17 it would be also great if you could visualize the custom field which already have some permissions configured. Or existing user/group permission could be displayed on the list (there is plenty of space) so that it's immediately visible which CFs are already available for editing via CEP and whom.

Thanks.
Radek

**Comment by clouless** [comment]
Hi Radek,

Sounds great. I will put it in the backlog. I am currently reworking the whole fields list anyway :)

**Comment by RJanata** [comment]
Thanks for quick reply and looking forward to redesigned field list! I'm open to do some beta testing - you code an addon for free, I test for free ;-)

**Comment by clouless** [comment]
Hi Radek,

Wow nice offer. That would be really great :)

I am currently on the Permission Editor Page.
And I will add some Filters too. And of course the Preview of permissions :)

![image](https://user-images.githubusercontent.com/12599965/28131716-10d37d5e-673b-11e7-921b-c8defb0ad3f1.png)

I will create a Beta-Test Task and once I have a running beta version I will contact you :)

cheers,
Bernhard

**Comment by RJanata** [comment]
Agreed :)

**Comment by clouless** [comment]
:white_check_mark: Done with [v2.0.0](https://codeclou.io/customfield-editor-plugin/2.0.0/release-notes/) - Released to Marketplace
