### ISSUE TITLE
Feature Request: Hide disabled or Sort by Enabled

### ISSUE THREAD

**Issue by mestevo** [codeclou/customfield-editor-plugin#39]
This the proper avenue for feature requests?

It would be really helpful if we could sort fields by their visibility or hide the disabled.  We've disabled a large number of values and it would make administration easier for my end users.

**Comment by clouless** [comment]
hi mestevo,

I am working on a redesign of the whole plugin and the List view will be changed a lot.
I will hide all disabled by default add a search functionality.
But you will have to wait some time. The features are planned to go live around the time the new AUI Colors will be in JIRA.
I think around 3-6 months at least.
