### ISSUE TITLE
Add permissions for project roles

### ISSUE THREAD

**Issue by fuertler** [codeclou/customfield-editor-plugin#40]
I'd like to add project roles as well (same as with standard JIRA sharing options, e.g., for filters). E.g., project administrators shall be enabled to modify custom fields.

![image](https://user-images.githubusercontent.com/34123467/33421110-56ef487e-d5b1-11e7-9717-92cc41ec6ec5.png)

**Comment by clouless** [comment]
This is not possible at the moment.
This feature is not planned, since it will have huge impact on the permission settings.
I will put the request in the backlog. At some point in the future this feature might get implemented, but I cannot guarantee it.

**Comment by clouless** [comment]
# duplicate of #25
