### ISSUE TITLE
[CEP-41] Bug: Updated Customfield Options should be updated in JIRA Issue as well

### ISSUE THREAD

**Issue by jkorpa** [codeclou/customfield-editor-plugin#41]
Hello!

We are using version 1.5.1 of Customfield Editor Plugin and have run into an issue whereby changing the value of a custom field via Customfield Editor Plugin does not show the updated value on issues.

The following steps were used to re-create the issue:

1.	Create an issue
2.	Assign to a part a number (ex. FDIMU - 709455 FDIMU GoNoGo)
3.	Change part number name in field editor 
a.	click ISSUES on top navigation banner
b.	click field editor
c.	Select project field to edit (ex. FDIMUSA)
d.	Click EDIT CHILD OPTIONS for field to edit (ex. FDIMU)
e.	Change part number name (ex. 713423 TDY A320 CF NEO to 713423 TDY A320FC)
4.	Navigate back to the issue created ealier (refresh page if necessary)
5.	Note that part number will reflect the original part number name and not the updated part number
6.	Change part number to a totally different part number (ex. 712775 0U2 A320 CF NEO)
7.	Note the part number is updated
8.	Change part number back to original part number and notice that the updated part number appears (ex. 713423 TDY A320FC).
9.	Note, after selecting original part number, the part number once again reflects old part number name, not the new (ex. 713423 TDY A320 CF NEO)

Kind Regards,

Jeff Korpa
Engineering Tools Specialist
 
501 Continental Blvd
El Segundo, CA 90245
www.teledyne-controls.com
Office: 310.765.3146

**Comment by clouless** [comment]
thanks for the bug report.
I will investigate, and release a bugfix release if necessary.

**Comment by clouless** [comment]
Ok I can verify this.
I have added a BDD Testcase to the Testsuite so that this bug never happens again.

![image](https://user-images.githubusercontent.com/12599965/34905020-f05d6ea2-f850-11e7-997f-f7cd50fc4f17.png)


I will shortly provide a Bugfix release

**Comment by clouless** [comment]
Bug is fixed in 1.5.3

![image](https://user-images.githubusercontent.com/12599965/34906834-7c74f6de-f875-11e7-993d-097885603848.png)

**Comment by clouless** [comment]
Version released https://codeclou.io/customfield-editor-plugin/1.5.3/release-notes/

**Comment by clouless** [comment]
Thanks for reporting :)
It was not so fast in my point of view :D but to write these tests takes a loooong time. 
The actual fix was one line of Code, but the test ensures that this Bug never appears again :)
