### ISSUE TITLE
Update of value through custom field editor is not reflected in the corresponding tickets

### ISSUE THREAD

**Issue by mliebelt** [codeclou/customfield-editor-plugin#5]
We had the following (strange) case with the custom field editor. Btw, a great tool we love a lot, thank you for that!!

This is how we have recreated the problem:

1. Defined a custom field "reg project" as a single selection list.
2. Added for that field in the custom field editor the permissions for some people.
3. They filled the list with value "project 1", "project 2"
4. They created a new ticket, and selected from the drop-down "reg project" "project 1".
5. They later decided that they would like to update the custom field.
6. Went to custom field editor, selected the custom field "reg project".
7. They went to the list, selected the line with "project 1", and updated the value on the left by a new value "project 11".
8. They visited then the already existing tickets, and found there the old value "project 1" under "reg project".
9. When trying to update the value, they could select the new value "project 11", but after saving the changes, they saw the old value "project 1" there.
10. They tried to create a new ticket, with "reg project" set to "project 11", but after saving it, they saw the old value "project 1" again.

This does not happen of course if the values are first deleted from the list of selection, and then added (as new value) to the list of values again.

**Comment by gruenebe** [comment]
Can you try to reindex JIRA first. Maybe this is the issue. I will try to do the same to see what is the reason.

**Comment by gruenebe** [comment]
Version v1.2.2 is released on Atlassian Marketplace. Just update Plugin via UPM.
Problem should be solved the next time you change the value.

ReleaseNoets:
https://codeclou.io/products/customfield-editor-plugin/information/releasenotes/#/scrollto/v122/

**Comment by mliebelt** [comment]
Thanks a lot for the fast and absolut fantastic reaction. We will upgrade as soon as we swich to JIRA 7 (which will need 2 more weeks).

**Comment by gruenebe** [comment]
Once you upgraded and also like the v1.2.2 version I am always happy about a positive review on the marketplace :smile:

**Comment by mliebelt** [comment]
Upgraded today to JIRA 7.1.1, so we are now able to incorporate the fix. Thank's a lot for the great support!

**Comment by gruenebe** [comment]
I am happy that everything works, thx for the review :)
