### ISSUE TITLE
authentication problem using rest api from another webserver (handle CORS Preflight HTTP Options request)

### ISSUE THREAD

**Issue by Tobbe08** [codeclou/customfield-editor-plugin#50]
Hi again

another problem Ive come across is accessing your api when using cors. When running api calls from another webserver I have to allow cors origin in jira webserver. This works fine for Jira built in api but when I try the same with your api I get a permission error.

Throwing the api url directly in the browser works fine for the same user so the user has access, thats for sure. but when executing it from another webserver.

[Error] Failed to load resource: the server responded with a status of 401 () (options, line 0)
[Error] Failed to load resource: Preflight response is not successful (options, line 0)
[Error] XMLHttpRequest cannot load https://xxxx/rest/jiracustomfieldeditorplugin/1/user/customfields/20603/contexts/25673/op.... Preflight response is not successful

I would very much appreciate if you could have a look.

and here is the code

function getRequestType() {
 
        debugger;
       var myResponse
       var url = "https://xxxxx/rest/jiracustomfieldeditorplugin/1/user/customfields/20603/contexts/25673/op...";
        var user = "xxxx";
        var password = "xxxxx";
        var xmlHttpRequest = new XMLHttpRequest();

       return new Promise(function(resolve, reject) {
  xmlHttpRequest.addEventListener("readystatechange", function () {
      if (this.readyState === 4) {
      myResponse = JSON.parse(this.responseText);
      resolve(myResponse);     

  // Create drop down menu with types
    myResponse.forEach(function(item){
    var option = document.createElement('option');
    option.value = item.id;
    option.innerHTML = item.optionvalue;
    requesttype.appendChild(option)
    })

    requesttype.onchange = function(){
    alert(this.value);
    }

      }
  });
        xmlHttpRequest.open("GET", url, false);
        xmlHttpRequest.setRequestHeader("Accept", "application/json");
        xmlHttpRequest.setRequestHeader("Content-Type", "application/json; charset=utf-8");
        xmlHttpRequest.setRequestHeader("Authorization", "Basic " + btoa(user + ":" + password));
    xmlHttpRequest.send(null);  
});

    }

**Comment by clouless** [comment]
hi,

First of all CORS needs to be handled by yourself and cannot be provided by the Plugin itself.
Jira has mechanism called "Whitelist" to enable CORS for certain domains. Where you need to whitelist your domain of the second webserver.
See: https://confluence.atlassian.com/adminjiraserver071/configuring-the-whitelist-802593145.html

If that fails your Apache Webserver or NGINX you put in Front of JIRA could manually override the CORS settings by serving the Preflight HTTP Options call for all REST calls.
What Webserver do you use in front of JIRA?

If you use Apache Webserver you could do: https://benjaminhorn.io/code/setting-cors-cross-origin-resource-sharing-on-apache-with-correct-response-headers-allowing-everything-through/

```
Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
Header set Access-Control-Max-Age "1000"
Header set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, authorization, accept, client-security-token"

# Added a rewrite to respond with a 200 SUCCESS on every OPTIONS request
RewriteEngine On
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ $1 [R=200,L]
```

This will always respond with HTTP 200 on any "HTTP Options" call. Which means the preflight request will pass.

I will test this myself and try to provide some code snippets. But generally CORS is something you need to handle by yourself. The plugin (and any other plugin providing a REST API) do not implement CORS explicitly, since this is a global JIRA thing.

**Comment by Tobbe08** [comment]
Sorry if I was unclear.
The code I provided works fine if I use a standard Jira API in the url. Its only when I use the url from your plugin it seems to fail.
The cors part I have taken care of already in my nginx server, and that part should be fine then since Jira standard api url works.

**Comment by clouless** [comment]
Ok then you can simply add this to you NGINX config to handle preflight requests then it should work

```
location /rest/jiracustomfieldeditorplugin/1 {
     if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'x-requested-with, Content-Type, origin, authorization, accept, client-security-token';
        #
        # Tell client that this pre-flight info is valid for 20 days
        #
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
     }
}
```

Source: https://enable-cors.org/server_nginx.html

**Comment by clouless** [comment]
And just for people who use **Apache Webserver** here is how to serve HTTP Options preflight request

```
<VirtualHost *:80>
    ServerName api-proxy.codeclou.io

    ## SSL  => You should use SSL (for demo we do not use it)
    #SSLEngine on
    #SSLCertificateKeyFile /etc/ssl.key/example.com.key
    #SSLCertificateFile /etc/ssl.crt/example.com.crt

    ## CORS Header
    Header always set Access-Control-Allow-Origin "*"
    Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
    Header always set Access-Control-Max-Age "1000"
    Header always set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, authorization, accept, client-security-token"

    ## Handle HTTP Options Preflight Request always with 200
    RewriteEngine On
    RewriteCond %{REQUEST_METHOD} OPTIONS
    RewriteRule ^(.*)$ $1 [R=200,L]

    ## Proxy to Jira Rest API
    <LocationMatch "/rest">
        ProxyPass http://192.168.178.11:17100/rest disablereuse=On
        ProxyPassReverse http:///192.168.178.11:17100/rest
    </LocationMatch>
</VirtualHost>
```

**Comment by clouless** [comment]
For me this is working. Here is my testcode for `index.html`

<html>
<head>
<title>customfield demo</title>
<script>
function getOptionsForCustomField() {
    var myResponse
    var url = "http://api-proxy.codeclou.io/rest/jiracustomfieldeditorplugin/1/user/customfields/10107/contexts/default/options";
    var user = "admin";
    var password = "admin";
    var xmlHttpRequest = new XMLHttpRequest();

    xmlHttpRequest.open("GET", url, false);
    xmlHttpRequest.setRequestHeader("Accept", "application/json");
    xmlHttpRequest.setRequestHeader("Content-Type", "application/json; charset=utf-8");
    xmlHttpRequest.setRequestHeader("Authorization", "Basic " + btoa(user + ":" + password));

    var promise = new Promise(function(resolve, reject) {
        xmlHttpRequest.addEventListener("readystatechange", function () {
            if (this.readyState === 4) {
              myResponse = JSON.parse(this.responseText);
              resolve(myResponse);
            }
        });
    });
    xmlHttpRequest.send(null);
    return promise;
}

document.addEventListener("DOMContentLoaded", function () {
    var customfieldSelect = document.getElementById('customfieldOptions');
    getOptionsForCustomField().then(function(options) {
        options.forEach(function(optionRest){
            var option = document.createElement('option');
            option.value = optionRest.id;
            option.innerHTML = optionRest.optionvalue;
            console.log(option);
            customfieldSelect.appendChild(option)
        });
    });
});

</script>
</head>
<body>

Customfield Options: <br>

<select id="customfieldOptions"></select>


</body>
</html>
```

**Comment by clouless** [comment]
✅ I added this to the rest api documentation: https://codeclou.io/customfield-editor-plugin/1.7.1/rest-api/
