### ISSUE TITLE
Hide field editor option if user has no permissions for it

### ISSUE THREAD

**Issue by justein230** [codeclou/customfield-editor-plugin#63]
We want to hide this option from users if they don't explicitly have permission to edit any fields. At the moment, you still see the Field Editor option, even if when you go to it your list will be empty. Is there any way this functionality can be implemented? Thanks.

Please have a look at the "How to Create an Issue" section on:

https://codeclou.io/customfield-editor-plugin/redirect/?/latest/issue-tracker/#howto

**Comment by clouless** [comment]
hi,
This feature is out of scope for the plugin. I want to keep such things simple and there is already a setting to hide admin-links from normal users. I do not plan to implement such a features since the user will not see any fields if he has no permissions.

**Comment by jasonsmith425** [comment]
I would say that if an admin wants something, it is in scope. I personally don't want to advertise the plugin to users (as many users are not responsible enough for it), but in certain situations i might want to offer it to users.
As it is now it is UI clutter for most users and it's annoying to be forced to accept that.

**Comment by clouless** [comment]
If you are talking about this link: 
![image](https://user-images.githubusercontent.com/12599965/49643753-d126b700-fa16-11e8-8499-e8b1e240c63f.png)

Then this would mean on every page reload/link click in JIRA I would have to evaluate if a user has any permissions on any customfields. This would mean at least one Database query.
This is not performant for the huge JIRA Installations with over 10000 Users I aim to support. That is one reason why this cannot be done.

Also is the link above the "entry point" to the plugin as described in all documentation pages. I do not want to hide it conditionally.
