### ISSUE TITLE
Ability to set field description on a custom field context

### ISSUE THREAD

**Issue by gornickj** [codeclou/customfield-editor-plugin#64]
Hello,

We utilize the custom field plugin and we have created "generic" fields the projects can customize to their liking. As these fields are labeled "List 1", "List 2" they have limited meaning to how teams are using them. Would it be possible, or have you considered the ability to add a description as well? I have done this at a global level, providing an override (using scriptrunner behaviours) - but we would need this to be project specific.  Is this something you would consider?

Thank you,

Jodi

**Comment by clouless** [comment]
Hi Jodi,

As I understand correctly you want the Customfield Description displayed in the Field Editor?
You are right the description is really missing there. I will publish a release 1.8.1 with the description tomorrow :) 

![image](https://user-images.githubusercontent.com/12599965/52816559-d1d86b00-30a1-11e9-8297-f292786b02e5.png)

![image](https://user-images.githubusercontent.com/12599965/52816571-d8ff7900-30a1-11e9-82a3-b2cb8c711798.png)

If this is not what you mean, maybe you can send me a screenshot :)

Cheers,

Bernhard

**Comment by gornickj** [comment]
Yes exactly, so that it would display under that field on edit/transition screens. It could override the default one provided by a field scheme. Using scriptrunner we do this by: formIssueType.setHelpText

**Comment by clouless** [comment]
Ok I do not know scriptrunner in detail and what it will set, but new version will display **fieldDescripton** and **contextDescription** like so:

![image](https://user-images.githubusercontent.com/12599965/52817617-ac992c00-30a4-11e9-85bc-f4a893153294.png)

![image](https://user-images.githubusercontent.com/12599965/52817671-d0f50880-30a4-11e9-9afd-f7ce83cf4b51.png)

![image](https://user-images.githubusercontent.com/12599965/52817706-ecf8aa00-30a4-11e9-8c9d-08f1c965e6d0.png)

Will this be enough?

**Comment by gornickj** [comment]
That looks to be the right setting. In our example I have the following:
![customfield display](https://user-images.githubusercontent.com/44605266/52818509-f8cc7800-3074-11e9-84b2-2c018944b734.png)

It displays on the screen as such:
![customfield description](https://user-images.githubusercontent.com/44605266/52818534-097cee00-3075-11e9-8a2d-b8c389208401.png)

I would like to use this to display my own text set in the custom field editor.

**Comment by clouless** [comment]
Ah ok now I understand :) You want to change the Customfield Description. 
I am sorry, but that is currently not possible via the plugin :( 

But I will put it in the backlog. But please be patient, since I currently have huge tasks to implement like DataCenter compatibility and many more.

You can watch the Roadmap for "progress" in:
https://github.com/codeclou/customfield-editor-plugin/projects/1

**Comment by gornickj** [comment]
I appreciate your consideration. We have provide generic fields for projects to use as they wish, but they do not like the "Names" as it does not relate to what they are using that field for. If we could get the ability to add a description as well it would solve a lot for us. I can do some by project today - that is what I use behaviours for, but this puts a huge admin burden and potentially performance so I try to limit how much we use these. Your plugin has been greatly received and being able to add a custom description on screen would make our users very happy.  Thank you.

**Comment by clouless** [comment]
I know the pain of JIRA administration :-/ And I put it on the Roadmap under "Feature Wishes". As soon as all the big tasks are done I really want to tackle all the small feature wishes. But even if they sound small, often they are very hard to implement. I wish you the best and hope the admin workload will decrease over time for you :-)

**Comment by gornickj** [comment]
Hello - I was wondering if you would consider your original idea of just adding the description area to the plugin. I have figured out how to read the description and display it per project. This would be very beneficial.

Thank you,

Jodi

**Comment by clouless** [comment]
Hi Jodi,

I was planning on releasing this feature with the next release in the next weeks together with final JIRA8 compatibility. I have implemented it already in [CEP-65](https://github.com/codeclou/customfield-editor-plugin/issues/65).

cheers,

Bernhard

**Comment by gornickj** [comment]
Awesome, thank you!!!
