### ISSUE TITLE
[CEP-66] JIRA 8.0 Release compatible

### ISSUE THREAD

**Issue by clouless** [codeclou/customfield-editor-plugin#66]
# Story

Make Plugin compatible to final 8.0.x Releases.

# Acceptance Criteria

 * ✅ Plugin is compatible to full version range

**Comment by clouless** [comment]
✅ done

![image](https://user-images.githubusercontent.com/12599965/53233989-de0a8c80-368e-11e9-9059-c45117b613a6.png)

**Comment by blop** [comment]
Any update on this?

**Comment by clouless** [comment]
It is released to the Marketplace on 26th of February, but currently in an approval process at Atlassian. 
With Version 1.9.0 and JIRA 8 compatibility the app transitions to a paid app.
We hope Atlassian will soon approve this version and make it available in the Marketplace. 

If you have further questions, you can use the ServiceDesk: https://codeclou-support.atlassian.net/servicedesk/customer/portal/1

**Comment by clouless** [comment]
released on Marketplace on 15th of March 2019.

**Comment by clouless** [comment]
### Jira 8.0.2 compatibility regression test

![image](https://user-images.githubusercontent.com/12599965/54419225-38838f80-4707-11e9-91d6-1cdff3a96895.png)

**Comment by clouless** [comment]
### Jira 8.1.0 compatibility regression test

![image](https://user-images.githubusercontent.com/12599965/55752371-194afa00-5a48-11e9-986b-780b610af8ab.png)


✅ Also manually smoke-tested in dockerized Data Center Setup with PostgreSQL Database:

 * https://github.com/codeclou/docker-atlassian-jira-data-center/tree/master/8.1.0

**Comment by clouless** [comment]
### Jira 8.2.0 compatibility regression test

 * Full test on dockerized datacenter Jira 8.2 with AdoptOpenJdk 11
 * https://github.com/codeclou/docker-atlassian-jira-data-center/tree/master/8.2.0
